### ISSUE TITLE
Never use shared data in multithread application.

### ISSUE THREAD

**Issue by dshumko** [AppliedGo/rest#1]
Please read this article [Share memory by communicating](https://blog.golang.org/share-memory-by-communicating) or this [Use a sync.Mutex or a channel?](https://github.com/golang/go/wiki/MutexOrChannel) 
and correct your code for work with shared data
`
k := p.ByName("key")
v := p.ByName("value")

data[k] = v
`

**Comment by christophberger** [comment]
Thanks for pointing this out. The code only serves for demoing how to send operations via REST/HTTP, hence MT safety was not on my radar. But I agree that the code is wrong at this point and should be corrected.

**Comment by christophberger** [comment]
Added a mutex to the code.
